# .travis.yml
# author: Seong Yong-ju ( @sei40kr )
---
language: node_js
node_js: 8
branches:
  only: master
git:
  depth: 1
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
  - yarn run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token:
    secure: 2zPE4EyMOSBzmQIhH+wACagZIFVe7buV5HnGHIQBrNs8l+y1X3hSFbDIkKWQ0JB3dk4EaRIFXi7VGQZ9n4ZtNpSN48/vcmgnLHhDWWy/S3vyX7Jzuz6GexMhykjVOxMVSOlit2VE7iUAFUvcRla19yiCdHttFUuSEF5xtgKpBdGOvTiNQB0VAhv2m9zz+JW6mmYFcyvyBOT++Brr3GEEKkETbNGxm0GccdDxCxnPMLOgtIfNdTI8obc5S6TWUiRU1PCFDpIpYN46gwqNxAEadecL29ZrJK3B9ZuDhGPOcqW9BBF6/BeGLe8eK7fnGcY1R1rCuyMcUYQZJwhnFqy5YvnOdm87JCYMJx3oRMVlhfLLGsLbE9Q3fRekK3MjmkevvpOLnOpToNmAxrCt4A9XNiTdeFDYoqFtNssqXaoS+gOYEWKmzGCcLd8NhU8Rph/mzoprRoiWQr5E72mPjVI6tVADRq8T05g99kyXNw2aisbWUP5xPbaeY3pWVMotbMf9pDtsItVRHxzL0ZkzodIO0S1aN6X5tjRAuboMt8lhtmlaE5GLIp7TmUx9AXOi5e5o3s9cQOjl7a0EkzWzzsdV9Iyjqjbka3fdDYoxE9IhjoMRLfHmpDup6xvFEJa8QekGntPti2B+kzE755xaL8oEUjBfhrmrUOfcaQObHJV1hEA=
after_deploy: ./cf-cache-flush.sh
