# .travis.yml
# author: Seong Yong-ju ( @sei40kr )
---
language: node_js
node_js: 8
branches:
  only: master
git:
  depth: 1
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
  - yarn run-script build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  github_token:
    secure: USAVNWLkbywx2AGytuvNCRjb31tkvMyqRtjodv3o9zcGl0Hp86HNpah7IySj5YgoJPB+SMrjEGM8PTNwlTJzvc51xGtb2fw/ANBdZK2duU2limJzxHYh6dvLAvO1FS6v7JWOCtftYg+gmfkEb4bjbZujgsWUQCbxTWgEqKGnkeN7FxVEaON0qONVXd4wjkNV+Pgc69gv+xSxE23TigPSINalmJ6CFPIThsgdp7rBDyN3UmdxIsriXFWOlo6R9fpMqk8mDGSiS8regT5bUgSc+RySL4TXyoSux31QijyMZq3yXeA4dOEoIsO4Eu1XZl/KkVVrgbOINEB6T8o1DjO2YzKFG0siY0/q932MeGJsLP4DxXo94/J/mgOR5GO9zaVR+BD5cLR6RtYlE3GT6jnKSoCVGojWDOlS0dF96sE/CJh6rQPMZPZYYEkjIV1ebL0PtIB+XJW4xmRFSjpMnTuTFcUugsRJWIe6ZIDUjsEXnas8djizjpQw0k/s7eDalbDXcuzeHY1GfNWqPxig46r6k09wEFKE28WQaEqVsVCIdxkeXcZYMkyelYalqb3J2NM5u3phzkn/sr4SMmtlsBTMnw8Bm+9yNT/VATFqjgPZczY5ZE7fL+ijC/DTWULnbmCAQAzOH0lugvWYFdkgZe7wy2+0ytakqjubsxGinjUvhgk=
after_deploy: ./cf-cache-flush.sh
